apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ARA_SHUTDOWN_DRAIN_SECONDS: {{ .Values.backend.shutdownDrainSeconds | quote }}
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
